image:
  repository: ghcr.io/pipery-dev/release-bot
  tag: 0ac1e55e7a4b65dc8eaf87917f830a11e5b9f363

imagePullSecrets:
  - name: ghcr-pull-secret

ingress:
  className: nginx

hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev
