image:
  repository: ghcr.io/pipery-dev/release-bot
  tag: 35b9b2da0c012243d1f360350c3dd15767680a69

imagePullSecrets:
  - name: ghcr-pull-secret
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: 
    - secretName: pipery.dev-wildcart
      hosts:
        - "*.pipery.dev"
hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev

