image:
  repository: ghcr.io/dexidp/dex
  tag: sha256-2e8700f4db24cabd6a37aaf8f84f61d091da82807e124bddd74ca7f137fd7703
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: auth.pipery.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: pipery.dev-wildcart
      hosts:
        - "*.pipery.dev"
