image:
  repository: ghcr.io/pipery-dev/auth
  tag: acbe929f907e1a9411b4dca6c66e75b954a46741

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: auth.pipery.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: pipery.dev-wildcart
      hosts:
        - "*.pipery.dev"
