---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: pipery
spec:
  encryptedData:
    .dockerconfigjson: AgAc/aSVANCC29HCA1ULXJJ8uHxCjxZezaXnLOW95kiEOWRxJgnLAUkxUcvKjt4HQZakSM6M6EKj86CssKxlpFEtHI5nmQ1wAT1oEAt7h/xGVljpMNQ2Rxm3OqcN/wcpJ6Fhz4H5Sf83cxMS6D9OTE1iYHy0ppKZjTmJuzfwSDBYtb88a5t9BR+wprdsufdUOiY4Z6/M5d84trLFhBs6Riut5SsfS8rOPBX7WwLK5O9J4emQ7b/TdneKmOjTF9nYbcOoX9cR07SI+O1E8M7Q0mEhRYW0KFnNzGAI1MuA4fZHwsjoWZ0qm7hGY1KPyB6i0H/EbTGTTvAK+4Y8P5YsjvR6nnLyMNhlzUlaxqeVAXR/7m/avzBObh1mRakZ2GoMJKH8v4S1Ax/404jHGPrw5gdRPIkPgiDZQDqOHtBWzZpRAVH5/W8p/cMr4JRHco/Nu65oaIo4mbS9QV44eHPI2m5dX6Omtlid5O+aDJro9IOZGgXq/IZyf7Pw0g7ghR6x5hha4yYbmzEE9wwL+3SWvlTyOn2GCFDQkk+pZUHKnwSz0bjJtd5Nsy9fcTc8wO4vNK2t148NE99L8N4smdSJ8EGkY8g8Idxkln9Ox+/O0GC+1r8bJLCfTRNrGa0bNvvGGlAA2GvbX7n/JGHm6R486VoMQ9cjE5ZKGjPVhr3wjNlrzoTxaNb4LoJ366x7S6vcaoK6nUTVYTmfb1HlEsq2RwYdHkyTan2T59jaMk3/0myF35928krMqkMxYxJjPogt9ag9o+VRenSAaPTpjpBdK4F3Id1crbjzVk+1Ceh7fZ0Iy3VEIbNEQwN3Qw6Et5lSYwyrRl4VdOgmwOXAb4ADHHZJq3WV86J8yStwcaSG9WoQ9MAe4dakhU4qdISHm9PNhDjB2hFWTgYFdWZDlspXBjOQh/bg+o+M6XAO+alolotuHJVcr5UktYfAC3Q=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: pipery
    type: kubernetes.io/dockerconfigjson
