---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: pipery
spec:
  encryptedData:
    .dockerconfigjson: AgA/OTTwmsVIrjRiwSlbLDQs3ieNdExHojswQ8Som5+dxNo6xM+Fk1Rg7/xv8qJkKIqXqcUGfCxNig8MTXHvDTlsxkTWCu4fMldLaCzOSEbhREsBWPYHa4SzTAAhe19OaQX2CCkpvhq+xqkUq2WW5/RmO6lsUYjnFjiLBlB4ENd7ANqQRiUPhmskiiVPq+s3s71JSrALOKbhOCvb1Flx77oIptpSbnYcP1DvkdKYGqdTj3vGnhWgBvHrGsJvB88yiZS+FvU1wk7Rwl+cDU1r9e+KADUs2MxMcwr/jvVkESYZ2WKTo5KWAitxvxoVTei+BqCXylXhPWgfUv3yTKgeXtCHK0jfY7k/059tPHseySoDbeGGgz7BTbk6uOZVkCfI3fA4lkG4+IySUxmZ9JggZU6ko0W/H2039Cy6lHqbCjOD2qk/vTT5sdud+mCfIxMz5T7oLRR8+PMPpjT5eRrIYrli/EM6u0OQD8VN1/K2nynzlM5/I/Glz8bz2zvJk95MUR3fxPig8wWaLLqjO1rs9/XtIQO9P5sQpcLzkg1ZmNTPgVofSxyuL7PHC0rM1vB3qZd3KwXdhaNkuTdp6rCaJ61RQgtXTxZgbgJ3JclVUTA1uwBPz0Y6R/p343ohI2Eq+I1LSkVsym2ItNCfyPzS3r5o7XpH29juuDBkGsf5B1uOvkGW3jgxn/C918VCNUdJtcykaf/fX8x6ZcoreGnPfLGZCPJyHJjXg5qQcxa5uS88S9h6UR8A87qZLZNHOwq/W1KBJvlRkyyDdVm4rkT1miXBjVH5WDtT2Bpe3LRj1hzZvsdimd0XAmO4mVf8W2dC06RHOh4qeD3UoWFLCAe6GsZc38abSLHvq8d+5YOfpO4Vxlv4a8gXDf7/ISearF+cRv/aaLPK9WUwzE/EQNdf/7UR556EnFaBiGYnElZkKiVVgvNh8uOavEUFM6w=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: pipery
    type: kubernetes.io/dockerconfigjson
