---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pipery-deploy-bot-database
  namespace: pipery
spec:
  encryptedData:
    database-url: AgAL4r018wiRaSuwCEEW16j1nTZnwJXOxlCvKsq6NZHn/qNxbzEObWIQKiHnztaHBzop5umigBXz4ZPB/rYnuIjaUbA0+ORCg2B5T/M8B7cnK08onZWmMn6wXJtr7Kn3tsinauEEXib5czIVhiMu/J+ThZCK1mk3x669blsnuc/K3bxpuWl00D0LEu0/9xJby0jwlfaFTzJuqhDpTb8iZazuYbfXN3hSSCtiFT2BVySrjyZO+L8e5dvk0tGnNw9J7zKn/1ROg9KFyclAl8KHAlPxBsPERwB0AW8tQXeVmqGusyh3Y15dTV2b83IsT5Li9WIqt0qvMUzpDirCL3XgeErk5oOh9mKGgeAtlvj4RSIbp4DbF6C/PAWIMGh9Yl33nRrodEG5HrLjuNlh2xP6IXzBXixuLhXvGKwitZQoYMEt2JktucxSU3cVwGmrfmB5uihIB0iA7iqiMJ+VHg12j/r497H8Z0Iydk/Y+x1azOGiGm2PDiIFbN1lSJx+kExZUPX8i6cDfXSxlonErTFDUNy6HD5L4Gkzc1CuXYsgTiwuXaIYb3g+wNmjTajccEtncSTNuNRhUAl/6NmWgrrNSD4SW5LRl46IRVWxgM+0GeYPiyewNv1qCy4MdmN015y4QhpERpZtZZZKxswqtQqRWC1/RralOH8/h0Uv7AmplOz2XPeOPvx3kRSmj2+umRXb5wMjoQQzRY6VVjMIjhZBqCZ2qO7DLmRPa8MG3y01/ICu/QmQZEmVuLxgn2Pi1Dx/DdA0Bi9VhHSnO17amvGUt0upWzdzV++fBeLWmjWYdr5MdfNHi0W2jO9IeUtK/MbIilOUmk5H0Zug
  template:
    metadata:
      name: pipery-deploy-bot-database
      namespace: pipery
