image:
  repository: ghcr.io/pipery-dev/deploy-bot
  tag: 424ed20033e69df473651c43da278cfb2c7baf50

imagePullSecrets:
  - name: ghcr-pull-secret

hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev
