image:
  repository: ghcr.io/pipery-dev/deploy-bot
  tag: d8e61081ec5519f81ee2d5de52b5c20c5b211d5f

imagePullSecrets:
  - name: ghcr-pull-secret
hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev

