image:
  repository: ghcr.io/pipery-dev/deploy-bot
  tag: 71f9aa64c2edb6b593b85d7d67d0212e1f247563

imagePullSecrets:
  - name: ghcr-pull-secret
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: 
    - secretName: pipery.dev-wildcart
      hosts:
        - "*.pipery.dev"
hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev

