apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipery-workflow-gen
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/pipery-dev/workflow-gen.git
      targetRevision: main
      path: charts/pipery-workflow-gen
      helm:
        valueFiles:
          - values.yaml
          - $values/applications/pipery-workflow-gen/values.yaml
    - repoURL: https://github.com/pipery-dev/argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: pipery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
