image:
  repository: ghcr.io/pipery-dev/workflow-gen
  tag: 11c15172d6f1eb97b790eadd5bb3ae3f50858c38

imagePullSecrets:
  - name: ghcr-pull-secret
ingress:
  className: nginx
hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev

