image:
  repository: ghcr.io/pipery-dev/workflow-gen
  tag: 188e622ea8e2b524bd0db205929e631d92c97d13

imagePullSecrets:
  - name: ghcr-pull-secret
hostAliases:
  - ip: 172.25.0.2
    hostnames:
      - auth.pipery.dev
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: 
    - secretName: pipery.dev-wildcart
      hosts:
        - "*.pipery.dev"
